name: On New Release

on:
  release:
    types: [published]  # Trigger only when a release is published

jobs:
  handle-new-release:
    runs-on: ubuntu-latest

    steps:
      - name: Print Release Info
        run: |
          echo "New release published!"
          echo "Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Body: ${{ github.event.release.body }}"
          echo "Published at: ${{ github.event.release.published_at }}"
      - name: Run the reusable action from branch
        uses: mozilla-mobile/testops-tools/.github/actions/firefox-ios-milestone@mb/firefox-ios-milestone
        with:
          release-name: ${{ github.event.release.name }}
          release-tag: ${{ github.event.release.tag_name }}
          testrail-host: ${{ secrets.TESTRAIL_HOST }}
          testrail-username: ${{ secrets.TESTRAIL_USERNAME }}
          testrail-api-key: ${{ secrets.TESTRAIL_PASSWORD }}  